spring:
  profiles:
    active: test

---
spring:
  profiles: test

storage:
  path: E:/storage
---

spring:
  profiles: production
  servlet:
    multipart:
      max-file-size: 500MB
      max-request-size: 500MB
storage:
  path: ${STORAGE_PATH}

server:
  port: 80